<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.0\ref\net8.0\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.entityframeworkcore\8.0.0\lib\net8.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.14" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.14">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrossCutting\CrossCutting.csproj" />
      <ProjectReference Include="..\OrganizationManagement.Contract\OrganizationManagement.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
