//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCutting.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CrossCutting.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string InsertLoginData {
            get {
                return ResourceManager.GetString("InsertLoginData", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        public static string WrongLoginData {
            get {
                return ResourceManager.GetString("WrongLoginData", resourceCulture);
            }
        }
        
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string DoYouWantToResetPassword {
            get {
                return ResourceManager.GetString("DoYouWantToResetPassword", resourceCulture);
            }
        }
        
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        public static string RePeatPassword {
            get {
                return ResourceManager.GetString("RePeatPassword", resourceCulture);
            }
        }
        
        public static string PasswordDontMatch {
            get {
                return ResourceManager.GetString("PasswordDontMatch", resourceCulture);
            }
        }
        
        public static string SuccessfullySignedUp {
            get {
                return ResourceManager.GetString("SuccessfullySignedUp", resourceCulture);
            }
        }
        
        public static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string TypeInYourNewPassword {
            get {
                return ResourceManager.GetString("TypeInYourNewPassword", resourceCulture);
            }
        }
        
        public static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        public static string Hosts {
            get {
                return ResourceManager.GetString("Hosts", resourceCulture);
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string ReleaseUsers {
            get {
                return ResourceManager.GetString("ReleaseUsers", resourceCulture);
            }
        }
        
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        public static string ReleaseUser {
            get {
                return ResourceManager.GetString("ReleaseUser", resourceCulture);
            }
        }
        
        public static string DoYouWantToReleaseUsers {
            get {
                return ResourceManager.GetString("DoYouWantToReleaseUsers", resourceCulture);
            }
        }
        
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        public static string PasswordMinOneCapitalLetter {
            get {
                return ResourceManager.GetString("PasswordMinOneCapitalLetter", resourceCulture);
            }
        }
        
        public static string PasswordMinOneLowerCaseLetter {
            get {
                return ResourceManager.GetString("PasswordMinOneLowerCaseLetter", resourceCulture);
            }
        }
        
        public static string PasswordNeedOneDigit {
            get {
                return ResourceManager.GetString("PasswordNeedOneDigit", resourceCulture);
            }
        }
        
        public static string PasswordMinOneAlphanumericCharacter {
            get {
                return ResourceManager.GetString("PasswordMinOneAlphanumericCharacter", resourceCulture);
            }
        }
        
        public static string CalendarOverview {
            get {
                return ResourceManager.GetString("CalendarOverview", resourceCulture);
            }
        }
        
        public static string WorkAreas {
            get {
                return ResourceManager.GetString("WorkAreas", resourceCulture);
            }
        }
        
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        public static string TimeTracking {
            get {
                return ResourceManager.GetString("TimeTracking", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string DoYouWantToLogout {
            get {
                return ResourceManager.GetString("DoYouWantToLogout", resourceCulture);
            }
        }
        
        public static string ReleasedUsers {
            get {
                return ResourceManager.GetString("ReleasedUsers", resourceCulture);
            }
        }
        
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        public static string HostFlow {
            get {
                return ResourceManager.GetString("HostFlow", resourceCulture);
            }
        }
        
        public static string ViewTeams {
            get {
                return ResourceManager.GetString("ViewTeams", resourceCulture);
            }
        }
        
        public static string ModifyTeam {
            get {
                return ResourceManager.GetString("ModifyTeam", resourceCulture);
            }
        }
        
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        public static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        public static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        public static string ViewTeam {
            get {
                return ResourceManager.GetString("ViewTeam", resourceCulture);
            }
        }
        
        public static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        public static string SuccessfullyAddedTeam {
            get {
                return ResourceManager.GetString("SuccessfullyAddedTeam", resourceCulture);
            }
        }
        
        public static string SuccessfullyModifiedTeam {
            get {
                return ResourceManager.GetString("SuccessfullyModifiedTeam", resourceCulture);
            }
        }
        
        public static string SuccessfullyDeletedEntries {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedEntries", resourceCulture);
            }
        }
        
        public static string ViewEmployees {
            get {
                return ResourceManager.GetString("ViewEmployees", resourceCulture);
            }
        }
        
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        public static string InviteEmployee {
            get {
                return ResourceManager.GetString("InviteEmployee", resourceCulture);
            }
        }
        
        public static string ModifyEmployee {
            get {
                return ResourceManager.GetString("ModifyEmployee", resourceCulture);
            }
        }
        
        public static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        public static string NoTeamAssigned {
            get {
                return ResourceManager.GetString("NoTeamAssigned", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteEmployees {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteEmployees", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteTeams {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteTeams", resourceCulture);
            }
        }
        
        public static string DeleteTeams {
            get {
                return ResourceManager.GetString("DeleteTeams", resourceCulture);
            }
        }
        
        public static string DeleteEmployees {
            get {
                return ResourceManager.GetString("DeleteEmployees", resourceCulture);
            }
        }
        
        public static string InsertEmployeeData {
            get {
                return ResourceManager.GetString("InsertEmployeeData", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string InviteSent {
            get {
                return ResourceManager.GetString("InviteSent", resourceCulture);
            }
        }
        
        public static string EmployeeModifiedSuccessfully {
            get {
                return ResourceManager.GetString("EmployeeModifiedSuccessfully", resourceCulture);
            }
        }
        
        public static string AccountConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("AccountConfirmedSuccessfully", resourceCulture);
            }
        }
        
        public static string ShiftPlan {
            get {
                return ResourceManager.GetString("ShiftPlan", resourceCulture);
            }
        }
        
        public static string InsertSmoobuApiKey {
            get {
                return ResourceManager.GetString("InsertSmoobuApiKey", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ApiKeyInvalid {
            get {
                return ResourceManager.GetString("ApiKeyInvalid", resourceCulture);
            }
        }
        
        public static string DoYouWantToChangeSettings {
            get {
                return ResourceManager.GetString("DoYouWantToChangeSettings", resourceCulture);
            }
        }
        
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        public static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        public static string ViewTags {
            get {
                return ResourceManager.GetString("ViewTags", resourceCulture);
            }
        }
        
        public static string ModifyTag {
            get {
                return ResourceManager.GetString("ModifyTag", resourceCulture);
            }
        }
        
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        public static string IsNonAccommodation {
            get {
                return ResourceManager.GetString("IsNonAccommodation", resourceCulture);
            }
        }
        
        public static string SuccessfullyModifiedTag {
            get {
                return ResourceManager.GetString("SuccessfullyModifiedTag", resourceCulture);
            }
        }
        
        public static string SuccessfullyAddedTag {
            get {
                return ResourceManager.GetString("SuccessfullyAddedTag", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteTags {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteTags", resourceCulture);
            }
        }
        
        public static string DeleteTags {
            get {
                return ResourceManager.GetString("DeleteTags", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        public static string InsertAppointmentData {
            get {
                return ResourceManager.GetString("InsertAppointmentData", resourceCulture);
            }
        }
        
        public static string SuccessfullyAddedAppointment {
            get {
                return ResourceManager.GetString("SuccessfullyAddedAppointment", resourceCulture);
            }
        }
        
        public static string ModifyAppointment {
            get {
                return ResourceManager.GetString("ModifyAppointment", resourceCulture);
            }
        }
        
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        public static string SuccessfullyModifiedAppointment {
            get {
                return ResourceManager.GetString("SuccessfullyModifiedAppointment", resourceCulture);
            }
        }
        
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        public static string EmptyTag {
            get {
                return ResourceManager.GetString("EmptyTag", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        public static string DoYouWantToStartTimeTracking {
            get {
                return ResourceManager.GetString("DoYouWantToStartTimeTracking", resourceCulture);
            }
        }
        
        public static string DoYouWantToStopTimeTracking {
            get {
                return ResourceManager.GetString("DoYouWantToStopTimeTracking", resourceCulture);
            }
        }
        
        public static string SuccessfullyStartedTimeTracking {
            get {
                return ResourceManager.GetString("SuccessfullyStartedTimeTracking", resourceCulture);
            }
        }
        
        public static string SuccessfullyStoppedTimeTracking {
            get {
                return ResourceManager.GetString("SuccessfullyStoppedTimeTracking", resourceCulture);
            }
        }
        
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteEntries {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteEntries", resourceCulture);
            }
        }
        
        public static string SuccessfullyAddedEmployee {
            get {
                return ResourceManager.GetString("SuccessfullyAddedEmployee", resourceCulture);
            }
        }
        
        public static string SuccessfullyAddedTimeTrackingEntry {
            get {
                return ResourceManager.GetString("SuccessfullyAddedTimeTrackingEntry", resourceCulture);
            }
        }
        
        public static string SuccessfullyModifiedTimeTrackingEntry {
            get {
                return ResourceManager.GetString("SuccessfullyModifiedTimeTrackingEntry", resourceCulture);
            }
        }
        
        public static string NotStampOutSince {
            get {
                return ResourceManager.GetString("NotStampOutSince", resourceCulture);
            }
        }
        
        public static string NotStampOutSinceInsertData {
            get {
                return ResourceManager.GetString("NotStampOutSinceInsertData", resourceCulture);
            }
        }
        
        public static string InsertTrackingGapHours {
            get {
                return ResourceManager.GetString("InsertTrackingGapHours", resourceCulture);
            }
        }
        
        public static string SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        public static string EmployeeAllowedEditTimeEntry {
            get {
                return ResourceManager.GetString("EmployeeAllowedEditTimeEntry", resourceCulture);
            }
        }
        
        public static string EmployeeAllowedManualTimeEntry {
            get {
                return ResourceManager.GetString("EmployeeAllowedManualTimeEntry", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        public static string CW {
            get {
                return ResourceManager.GetString("CW", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
    }
}
